// Generated source.
// Generator: org.chromium.sdk.internal.wip.tools.protocolgenerator.Generator
// Origin: http://svn.webkit.org/repository/webkit/!svn/bc/93101/trunk/Source/WebCore/inspector/Inspector.json@93101

package org.chromium.sdk.internal.wip.protocol.input;

public class GeneratedParserInterfaceList {
  public static final Class<?>[] LIST = {
    org.chromium.sdk.internal.wip.protocol.input.debugger.BreakpointResolvedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.CallFrameValue.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.DebuggerWasDisabledEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.DebuggerWasEnabledEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.EvaluateOnCallFrameData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.GetScriptSourceData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.LocationValue.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.PausedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.PausedEventData.Details.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.ResumedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.ScopeValue.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.ScriptFailedToParseEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.ScriptParsedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.SetBreakpointByUrlData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.SetBreakpointData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.SetScriptSourceData.class,
    org.chromium.sdk.internal.wip.protocol.input.debugger.SetScriptSourceData.Result.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.BringToFrontEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.DidCreateWorkerEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.DidDestroyWorkerEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.DisconnectFromBackendEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.EvaluateForTestInFrontendEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.FrontendReusedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.InspectEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.InspectEventData.Hints.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.ResetEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.ShowPanelEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.inspector.StartUserInitiatedDebuggingEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.DomContentEventFiredEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.FrameDetachedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.FrameNavigatedEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.FrameResourceTreeValue.class,
    org.chromium.sdk.internal.wip.protocol.input.page.FrameResourceTreeValue.Resources.class,
    org.chromium.sdk.internal.wip.protocol.input.page.FrameValue.class,
    org.chromium.sdk.internal.wip.protocol.input.page.GetCookiesData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.GetResourceContentData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.GetResourceTreeData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.LoadEventFiredEventData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.SearchInResourcesData.class,
    org.chromium.sdk.internal.wip.protocol.input.page.SearchResultValue.class,
    org.chromium.sdk.internal.wip.protocol.input.runtime.CallFunctionOnData.class,
    org.chromium.sdk.internal.wip.protocol.input.runtime.EvaluateData.class,
    org.chromium.sdk.internal.wip.protocol.input.runtime.GetPropertiesData.class,
    org.chromium.sdk.internal.wip.protocol.input.runtime.PropertyDescriptorValue.class,
    org.chromium.sdk.internal.wip.protocol.input.runtime.RemoteObjectValue.class,
  };
}
